<?php


use Drupal\Core\Form\FormStateInterface;
function first_form_second_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $form['phone_number']['#title'] = t('Start with + and your country code.');


  
  }
function first_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) 
{
	if($form_id == 'user_login_form')
	{
		$form['name'] = array(
      '#type' => 'textfield',
      '#title' => t('name'),
    );
	}
	
	if($form_id == 'second_form')
	{
		$form['phone_number'] = array(
      '#type' => 'tel',
      '#title' => t('name'),
    );
	}
}
 

 function first_entity_presave(Drupal\Core\Entity\EntityInterface $entity) 
 {

	 
	 $node = \Drupal::routeMatch()->getParameter('node');
if ($node) {
  // You can get nid and anything else you need from the node object.
  echo $nid = $node->id();
}

$node = \Drupal\node\Entity\Node::load($nid);
//kint($node);
echo $node->title->value.'<br>'; 

	echo $node->original->title->value;
echo $node->moderation_state->target_id;
echo $moderation_state = $entity->get('moderation_state')->getString();


die;
	 
 }


?>